name: build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build addon
        run: python dev.py build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: cityGen.zip
          name: cityGen.zip
