# Create a release for the blender addon
# Has to be started manually

name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "version"
        required: true
        default: "0.0.0"

permissions:
  contents: write

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Addon
        uses: blenderkit/blender-addon-build@main
        with:
          name: cityGen
          exclude-files: ".git;.gitignore;README.md"
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Release Addon
        uses: blenderkit/blender-addon-release@main
        with:
          artifact_name: cityGen
          release_name: cityGen
          version: ${{github.event.inputs.version}}
