name: test
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  setup:
    uses: ./setup.yml
    secrets:
      assets-gitlab-token: ${{ secrets.ASSETS_GITLAB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: python dev.py test
