name: test
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      - name: Set up Git credentials for GitLab
        run: |
          git config --global url."https://oauth2:${{ secrets.VILLEVITE_LFS_TOKEN }}@gitlab.hpi.com/".insteadOf "https://gitlab.hpi.com/"
      - name: Initialize and update submodules
        run: |
          git submodule update --init

      - name: Cache Blender installations
        id: blender-cache
        uses: actions/cache@v4
        with:
          path: ./blender
          key: ${{ runner.os }}-blender-${{ hashFiles('./dev.py') }}
          restore-keys: |
            ${{ runner.os }}-blender-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11


      - name: Run tests
        run: python dev.py test
