name: test
on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0
      - name: Set up Git credentials for GitLab
        run: |
          git config --global url."https://oauth2:${{ secrets.VILLEVITE_LFS_TOKEN }}@gitlab.hpi.de/".insteadOf "https://gitlab.hpi.de/"

      - name: Get submodule commit hash
        id: submodule-hash
        run: |
          SUBMODULE_PATH="villevite/Assets"
          HASH=$(git ls-tree HEAD $SUBMODULE_PATH | awk '{print $3}')
          echo "hash=$HASH" >> $GITHUB_OUTPUT

      - name: Restore submodule cache
        uses: actions/cache@v4
        with:
          path: villevite/Assets
          key: assets-submodule-${{ steps.submodule-hash.outputs.hash }}
          restore-keys: |
            assets-submodule-
      - name: Sync submodule
        run: |
          git submodule sync
      - name: Init and update submodules (rebuild .git dirs)
        run: |
          git submodule update --init --force --recursive

      - name: Cache Blender installations
        id: blender-cache
        uses: actions/cache@v4
        with:
          path: ./blender
          key: ${{ runner.os }}-blender-${{ hashFiles('./dev.py') }}
          restore-keys: |
            ${{ runner.os }}-blender-

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11


      - name: Run tests
        run: python dev.py test
